### ISSUE TITLE
doesnt redirect to subcriptions page

### ISSUE THREAD

**Issue by wttsuk4** [longzheng/chrome-subscribe-save-oneclick-cancel#3]
Hii have clicked unsubcribe 30 but after doing 1 it dosent go back to subscriptions page?

**Comment by longzheng** [comment]
I've seen it randomly happen but haven't pinned down the cause.

**Comment by wttsuk4** [comment]
any update possible and any to remove saved addresses?

**Comment by gergor888** [comment]
This is the behavior I always get. I use brave browser not sure if it makes any difference.

**Comment by gergor888** [comment]
Can you automate an extra click on "Deliveries" in the page after each cancellation so it'll bring it back to the proper page to let the script continue?

**Comment by longzheng** [comment]
I finally reproduced this, it's because on a smaller screen the Amazon "recommendations" box on the "Deliveries" page takes up a lot of room which prevents the subscriptions from loading for the extension to be able to trigger the next cancellation correctly.

I've changed it to redirect to the "Subscriptions" page after cancelling one which seems to be more reliable.

I've published a new version 1.0.6 (pending Google review).

**Comment by jasonfrancki** [comment]
just came across this extension and installed 1.0.6 - seemed to have this issue still... after cancelling one item, it loads a page full of recommendations and does not go back to my "Subscriptions" page.  As soon as I manually click to go back, it begins the script to cancel the next item.

Even still, it was a big time saver for cancelling my 70 subscriptions - appreciate your efforts on this!

**Comment by longzheng** [comment]
> just came across this extension and installed 1.0.6 - seemed to have this issue still... after cancelling one item, it loads a page full of recommendations and does not go back to my "Subscriptions" page.  As soon as I manually click to go back, it begins the script to cancel the next item.
> 
> Even still, it was a big time saver for cancelling my 70 subscriptions - appreciate your efforts on this!

Ah that's weird, it should be redirecting to the subscriptions page.

Do you mind sharing the URL you end up with after cancelling one item? (The URL should be safe to share, it doesn't contain any sensitive data)

**Comment by jasonfrancki** [comment]
> > just came across this extension and installed 1.0.6 - seemed to have this issue still... after cancelling one item, it loads a page full of recommendations and does not go back to my "Subscriptions" page.  As soon as I manually click to go back, it begins the script to cancel the next item.
> > Even still, it was a big time saver for cancelling my 70 subscriptions - appreciate your efforts on this!
> 
> Ah that's weird, it should be redirecting to the subscriptions page.
> 
> Do you mind sharing the URL you end up with after cancelling one item? (The URL should be safe to share, it doesn't contain any sensitive data)

Sorry I manually clicked back and already deleted all subscriptions so I can't reproduce it at the moment

**Comment by gergor888** [comment]
I updated to 1.0.6 and it still took me to "Explore Subscribe & Save" instead of back to "Subscriptions"

I ran a testcase and this is what it took me after the "one click cancel"
https://www.amazon.com/fmc/everyday-essentials-sns?snsActionCompleted=cancelSubscription&ASIN=B00UTFZB82&canceledNextDeliveryDate=1763280000000&ref_=rcxsubs_redir_newmys_cancel_redir_sdp&expiration=1762498557&subscriptionId=SNST0_XGEKN2MPPSPSRCVX1EBR&shipId=jmkjoroolo

**Comment by longzheng** [comment]
Right I see Amazon US has "everyday essentials subscribe and save" under a different URL. My extension was only watching `/auto-deliveries` and `/gp/subscribe-and-save`.

I'm pushing a new version that will watch for all URLs and hopefully fix these regional variations.
